Project_63133655/Project_63133655/Controllers/XuatKho_63133655Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63133655.Models;

namespace Project_63133655.Controllers
{
    public class XuatKho_63133655Controller : Controller
    {
        private Project_63133655Entities db = new Project_63133655Entities();

        // GET: XuatKho_63133655
        public ActionResult Index()
        {
            var xUATKHO = db.XUATKHO.Include(x => x.NHANVIEN);
            return View(xUATKHO.ToList());
        }
        [HttpPost]
        public ActionResult Index(string SoPhieuXuat)
        {
            var timXUATKHO = db.XUATKHO.SqlQuery("exec TIMKIEM_XUATKHO '" + SoPhieuXuat + "' ");
            return View(timXUATKHO.ToList());
        }

        // GET: XuatKho_63133655/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            XUATKHO xUATKHO = db.XUATKHO.Find(id);
            string fSave = Server.MapPath("/saveID.txt");
            string[] soID = { xUATKHO.SoPhieuXuat };
            System.IO.File.WriteAllLines(fSave, soID);
            if (xUATKHO == null)
            {
                return HttpNotFound();
            }
            return View(xUATKHO);
        }

        // GET: XuatKho_63133655/Create
        public ActionResult Create()
        {
            ViewBag.MaNV = new SelectList(db.NHANVIEN, "MaNV", "HoNV");
            return View();
        }

        // POST: XuatKho_63133655/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SoPhieuXuat,NgayXuat,MaNV,TenNgNhan,DiaChi,SDT")] XUATKHO xUATKHO)
        {
            if (ModelState.IsValid)
            {
                db.XUATKHO.Add(xUATKHO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNV = new SelectList(db.NHANVIEN, "MaNV", "HoNV", xUATKHO.MaNV);
            return View(xUATKHO);
        }

        // GET: XuatKho_63133655/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            XUATKHO xUATKHO = db.XUATKHO.Find(id);
            if (xUATKHO == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNV = new SelectList(db.NHANVIEN, "MaNV", "HoNV", xUATKHO.MaNV);
            return View(xUATKHO);
        }

        // POST: XuatKho_63133655/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SoPhieuXuat,NgayXuat,MaNV,TenNgNhan,DiaChi,SDT")] XUATKHO xUATKHO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(xUATKHO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNV = new SelectList(db.NHANVIEN, "MaNV", "HoNV", xUATKHO.MaNV);
            return View(xUATKHO);
        }

        // GET: XuatKho_63133655/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            XUATKHO xUATKHO = db.XUATKHO.Find(id);
            if (xUATKHO == null)
            {
                return HttpNotFound();
            }
            return View(xUATKHO);
        }

        // POST: XuatKho_63133655/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            XUATKHO xUATKHO = db.XUATKHO.Find(id);
            db.XUATKHO.Remove(xUATKHO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63133655/Project_63133655/Views/XuatKho_63133655/Create.cshtml
@model Project_63133655.Models.XUATKHO

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>XUẤT KHO</h2>


@using (Html.BeginForm("Create", "XuatKho_63133655", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tạo phiếu xuất kho</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SoPhieuXuat, "Số phiếu xuất", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoPhieuXuat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoPhieuXuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayXuat, "Ngày xuất", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayXuat, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.NgayXuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNV, "Nhân viên phụ trách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNgNhan, "Tên người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNgNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNgNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, "Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_63133655/Project_63133655/Views/XuatKho_63133655/Delete.cshtml
@model Project_63133655.Models.XUATKHO

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>XUẤT KHO</h2>

<h3>Bạn có chắc chắn muốn xóa phiếu này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Số phiếu nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoPhieuXuat)
        </dd>

        <dt>
            Ngày nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayXuat)
        </dd>

        <dt>
            Nhân viên phụ trách
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNV)
        </dd>

        <dt>
            Tên người nhận
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNgNhan)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project_63133655/Project_63133655/Views/XuatKho_63133655/Details.cshtml
@model Project_63133655.Models.XUATKHO

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>XUẤT KHO</h2>

<div>
    <h4>Chi tiết phiếu </h4>
    @Html.ActionLink("Xem nội dung chi tiết", "Index", "NDXuatKho_63133655")
<dl class="dl-horizontal">
    <dt>
        Số phiếu nhập
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SoPhieuXuat)
    </dd>

    <dt>
        Ngày nhập
    </dt>

    <dd>
        @Html.DisplayFor(model => model.NgayXuat)
    </dd>

    <dt>
        Nhân viên phụ trách
    </dt>

    <dd>
        @Html.DisplayFor(model => model.MaNV)
    </dd>

    <dt>
        Tên người nhận
    </dt>

    <dd>
        @Html.DisplayFor(model => model.TenNgNhan)
    </dd>

    <dt>
        Địa chỉ
    </dt>

    <dd>
        @Html.DisplayFor(model => model.DiaChi)
    </dd>

    <dt>
        Số điện thoại
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SDT)
    </dd>
</dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.SoPhieuXuat }) |
    @Html.ActionLink("Xóa", "Delete", new { id = Model.SoPhieuXuat }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

Project_63133655/Project_63133655/Views/XuatKho_63133655/Edit.cshtml
@model Project_63133655.Models.XUATKHO

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>XUẤT KHO</h2>


@using (Html.BeginForm("Edit", "XuatKho_63133655", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chỉnh sửa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SoPhieuXuat, "Số phiếu xuất", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoPhieuXuat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoPhieuXuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayXuat, "Ngày xuất", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayXuat, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.NgayXuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNV, "Nhân viên phụ trách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNgNhan, "Tên người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNgNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNgNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, "Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_63133655/Project_63133655/Views/XuatKho_63133655/Index.cshtml
@model IEnumerable<Project_63133655.Models.XUATKHO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "SoPhieuXuat", rowsPerPage: 10);
}

<h2>XUẤT KHO</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

        .alternatingRowStyle {
            background-color: #FFFAEE;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "XuatKho_63133655", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
        <table class="table1" align="center">
            <tr>
                <td>
                    <div> Số phiếu</div>
                </td>
                <td>
                    <input type="text" name="SoPhieuXuat" value="@ViewBag.SoPhieuXuat" />
                </td>
            </tr>
            
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
                background-color: #FFC52D;color:white" />
                    <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
                background-color: #FFC52D;color:white" onclick="location.href='@Url.Action("Index", "XuatKho_63133655/Index")'" />
                </td>
            </tr>
        </table>
        }
    </div>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
              {
                    grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                    grid.Column("SoPhieuXuat","Số phiếu xuất"), //the model fields to display
                    grid.Column("NgayXuat","Ngày xuất",format:@<text> @item.NgayXuat.ToString("dd/MM/yyyy")</text>),
                    grid.Column("MaNV","Nhân viên phụ trách"),
                    grid.Column("TenNgNhan","Tên người nhận"),
                    grid.Column("DiaChi","Địa chỉ"),
                    grid.Column("SDT","Số điện thoại"),
                    grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","XuatKho_63133655", new { id = item.SoPhieuXuat },"XuatKho_63133655Controller")),
                    grid.Column(format: (item) => Html.ActionLink("Sửa", "Edit","XuatKho_63133655", new { id = item.SoPhieuXuat },"XuatKho_63133655Controller")),
                    grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","XuatKho_63133655", new { id = item.SoPhieuXuat },"XuatKho_63133655Controller")),
              }
        )
    </div>
</body>
</html>