ThiGK_63133655/ThiGK_63133655/Controllers/DocGia_63133655Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThiGK_63133655.Models;

namespace ThiGK_63133655.Controllers
{
    public class DocGia_63133655Controller : Controller
    {
        private ThiGK_63133655Entities db = new ThiGK_63133655Entities();

        public ActionResult GioiThieu_63133655()
        {
            return View();
        }

        public ActionResult TimKiemDG_63133655()
        {
            var docGias = db.DocGia.Include(n => n.LoaiDG);
            return View(docGias.ToList());
        }
        [HttpPost]
        public ActionResult TimKiemDG_63133655(string maDG, string HoTen)
        {

            var docGias = db.DocGia.SqlQuery("exec TimKiem '" + maDG + "', N'" + HoTen + "' ");        
            if (docGias.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            return View(docGias.ToList());
        }

        // GET: DocGia_63133655
        public ActionResult Index()
        {
            var docGia = db.DocGia.Include(d => d.LoaiDG);
            return View(docGia.ToList());
        }

        // GET: DocGia_63133655/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocGia docGia = db.DocGia.Find(id);
            if (docGia == null)
            {
                return HttpNotFound();
            }
            return View(docGia);
        }

        // GET: DocGia_63133655/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiDG = new SelectList(db.LoaiDG, "MaLoaiDG", "TenLoaiDG");
            return View();
        }

        // POST: DocGia_63133655/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDG,HoDG,TenDG,NgaySinh,GioiTinh,Email,AnhDG,MaLoaiDG")] DocGia docGia)
        {
            var imgDG = Request.Files["Avatar"];
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(imgDG.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            imgDG.SaveAs(path);
            if (ModelState.IsValid)
            {
                docGia.AnhDG = postedFileName;
                db.DocGia.Add(docGia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiDG = new SelectList(db.LoaiDG, "MaLoaiDG", "TenLoaiDG", docGia.MaLoaiDG);
            return View(docGia);
        }

        // GET: DocGia_63133655/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocGia docGia = db.DocGia.Find(id);
            if (docGia == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiDG = new SelectList(db.LoaiDG, "MaLoaiDG", "TenLoaiDG", docGia.MaLoaiDG);
            return View(docGia);
        }

        // POST: DocGia_63133655/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDG,HoDG,TenDG,NgaySinh,GioiTinh,Email,AnhDG,MaLoaiDG")] DocGia docGia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(docGia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiDG = new SelectList(db.LoaiDG, "MaLoaiDG", "TenLoaiDG", docGia.MaLoaiDG);
            return View(docGia);
        }

        // GET: DocGia_63133655/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocGia docGia = db.DocGia.Find(id);
            if (docGia == null)
            {
                return HttpNotFound();
            }
            return View(docGia);
        }

        // POST: DocGia_63133655/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DocGia docGia = db.DocGia.Find(id);
            db.DocGia.Remove(docGia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThiGK_63133655/ThiGK_63133655/Views/DocGia_63133655/Create.cshtml
@model ThiGK_63133655.Models.DocGia

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>NHẬP THÔNG TIN ĐỘC GIẢ</h2>


@using (Html.BeginForm("Create", "DocGia_63133655", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaDG, "Mã độc giả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoDG, "Họ độc giả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoDG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDG, "Tên độc giả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    <label>Nam @Html.RadioButton("GioiTinh", true, new { @checked = "checked" })</label>
                    <label>Nữ @Html.RadioButton("GioiTinh", false)</label>
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhDG, "Ảnh đại diện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Avatar" accept="image" />
                @Html.ValidationMessageFor(model => model.AnhDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiDG, "Loại độc giả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiDG", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThiGK_63133655/ThiGK_63133655/Views/DocGia_63133655/Delete.cshtml
@model ThiGK_63133655.Models.DocGia

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<h3>Bạn có chắc muốn xóa bảng này?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoDG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoDG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenDG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhDG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhDG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiDG.TenLoaiDG)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiDG.TenLoaiDG)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

ThiGK_63133655/ThiGK_63133655/Views/DocGia_63133655/Details.cshtml
@model ThiGK_63133655.Models.DocGia

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    <link href="~/Content/StyleSheet.css" rel="stylesheet" />
    string gtinh = "";
}

<h2>Chi tiết</h2>
<div class="container">
    <div class="column">
        <img src="~/Images/@Html.DisplayFor(model => model.AnhDG)" class="avatar" alt="Avatar">
    </div>
    <div class="column">
        Mã độc giả:<br />
        Họ độc giả:<br />
        Tên độc giả:<br />
        Giới tính:<br />
        Ngày sinh:<br />
        Email:<br />
        Loại độc giả:<br />
    </div>
    <div class="column">
        @Html.DisplayFor(model => model.MaDG) <br />
        @Html.DisplayFor(model => model.HoDG) <br />
        @Html.DisplayFor(model => model.TenDG)<br />
        @{if (Model.GioiTinh == true)
            { gtinh = "Nam"; }
            else
            { gtinh = "Nữ"; }
        }
        @gtinh<br />
        @Html.DisplayFor(model => model.NgaySinh)<br />
        @Html.DisplayFor(model => model.Email)<br />
        @Html.DisplayFor(model => model.LoaiDG.TenLoaiDG)<br />
    </div>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaDG }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

ThiGK_63133655/ThiGK_63133655/Views/DocGia_63133655/Edit.cshtml
@model ThiGK_63133655.Models.DocGia

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DocGia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDG)

        <div class="form-group">
            @Html.LabelFor(model => model.HoDG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoDG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhDG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhDG, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiDG, "MaLoaiDG", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiDG", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiDG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThiGK_63133655/ThiGK_63133655/Views/DocGia_63133655/GioiThieu_63133655.cshtml
@{
    ViewBag.Title = "GioiThieu_63133655";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    <link href="~/Content/StyleSheet.css" rel="stylesheet" />
}

<div class="container">
    <h4>THÔNG TIN SINH VIÊN DỰ THI</h4>
    <div class="column">
        <img src="~/Images/giothieu.png" class="avatar" alt="Avatar">
    </div>
    <div class="column">
        Mã số SV:</br>
        Họ và tên:</br>
        Ngày thi:</br>
        Học phần:
    </div>
    <div class="column">
        63133655</br>
        Nguyễn Hoài Huy Đạt</br>
        26/10/2023</br>
        Phát triển ứng dụng web
    </div>
</div>

ThiGK_63133655/ThiGK_63133655/Views/DocGia_63133655/Index.cshtml
@model IEnumerable<ThiGK_63133655.Models.DocGia>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenDG", rowsPerPage: 2);
    string gtinh = "";
    int i = 0;
}

<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
              {
                    grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                    grid.Column("MaDG","Mã độc giả"), //the model fields to display
                    grid.Column("HoDG","Họ độc giả"  ),
                    grid.Column("TenDG","Tên độc giả"),
                    grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
                    grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
                    grid.Column("AnhDG","Ảnh độc giả"),
                    grid.Column("Email","Email"),
                    grid.Column("LoaiDG.TenLoaiDG","Loại độc giả"),
                    grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","DocGia_63133655", new { id = item.MaDG },"DocGia_63133655Controller")),
}
)
    </div>
</body>
</html>

ThiGK_63133655/ThiGK_63133655/Views/DocGia_63133655/TimKiemDG_63133655.cshtml
@{
    ViewBag.Title = "TimKiemDG_63133655";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenDG", rowsPerPage: 2);
}

<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("TimKiemDG_63133655", "DocGia_63133655", FormMethod.Post))
        {
            @Html.AntiForgeryToken()


            <table class="table1" align="center">
                <tr>
                    <td>
                        <div> Mã độc giả</div>
                    </td>
                    <td>
                        <input type="text" name="maDG" value="@ViewBag.maDG" />
                    </td>

                </tr>
                <tr>
                    <td>Họ tên</td>
                    <td>
                        <input type="text" name="hoTen" value="@ViewBag.hoTen" />
                    </td>

                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" />
                        <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" onclick="location.href='@Url.Action("TimKiemDG_63133655", "DocGia_63133655/TimKiemDG_63133655")'" />

                    </td>
                </tr>
            </table>
        }
    </div>
    <body>
        <div id="gridContent">
            @ViewBag.TB
            @grid.GetHtml(
                     tableStyle: "table table-bordered table-hover",
                     footerStyle: "grid-footer",
                     fillEmptyRows: true,
                     mode: WebGridPagerModes.Numeric,
                     alternatingRowStyle: "alternatingRowStyle",
                       columns: new[]  // colums in grid
                       {
                        grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                        grid.Column("MaDG","Mã độc giả"), //the model fields to display
                        grid.Column("HoDG","Họ độc giả"  ),
                        grid.Column("TenDG","Tên độc giả"),
                        grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
                        grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
                        grid.Column("AnhDG","Ảnh độc giả"),
                        grid.Column("Email","Email"),
                        grid.Column("LoaiDG.TenLoaiDG","Loại độc giả"),
                        grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","DocGia_63133655", new { id = item.MaDG },"DocGia_63133655Controller")),
                       }
                             )
        </div>
    </body>
</html>